<?php
declare(strict_types=1);namespace App\Controllers\Admin;
use App\Core\Controller;use App\Core\Database;use PDO;
class ReviewController extends Controller{
 public function index():void{$pdo=Database::connection();$_SESSION['csrf_token']??=bin2hex(random_bytes(32));if($_SERVER['REQUEST_METHOD']==='POST')$this->post($pdo);$reviews=$pdo->query('SELECT * FROM testimonials ORDER BY FIELD(status,\'pending\',\'approved\',\'rejected\'),sort_order,id DESC')->fetchAll();$edit=null;$id=filter_input(INPUT_GET,'edit',FILTER_VALIDATE_INT);if($id){$s=$pdo->prepare('SELECT * FROM testimonials WHERE id=?');$s->execute([$id]);$edit=$s->fetch()?:null;}$flash=$_SESSION['review_admin_flash']??null;unset($_SESSION['review_admin_flash']);$this->view('layouts/admin-layout',['title'=>'Reviews','showPageTitle'=>false,'content'=>$this->render('admin/reviews/index',compact('reviews','edit','flash')+['csrfToken'=>$_SESSION['csrf_token']])]);}
 private function post(PDO $pdo):never{if(!hash_equals((string)($_SESSION['csrf_token']??''),(string)($_POST['csrf_token']??''))){http_response_code(419);exit('Invalid request token.');}$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT)?:null;$action=(string)($_POST['action']??'save');if($action==='delete'&&$id){$pdo->prepare('DELETE FROM testimonials WHERE id=?')->execute([$id]);$this->go('Review deleted.');}$name=trim((string)($_POST['reviewer_name']??''));$text=trim((string)($_POST['review_text']??''));if($name===''||$text==='')$this->go('Name and review are required.','error',$id);$avatar='';if($id){$s=$pdo->prepare('SELECT avatar_path FROM testimonials WHERE id=?');$s->execute([$id]);$avatar=(string)($s->fetchColumn()?:'');}try{$avatar=$this->upload($_FILES['avatar']??null)??$avatar;}catch(\RuntimeException $e){$this->go($e->getMessage(),'error',$id);}$rating=max(1,min(5,(int)($_POST['rating']??5)));$status=in_array($_POST['status']??'', ['pending','approved','rejected'],true)?$_POST['status']:'pending';$data=[$name,trim((string)($_POST['reviewer_email']??'')),trim((string)($_POST['reviewer_role']??'')),$avatar?:null,trim((string)($_POST['title']??'')),$text,$rating,$status,max(0,(int)($_POST['sort_order']??0))];if($id)$pdo->prepare('UPDATE testimonials SET reviewer_name=?,reviewer_email=?,reviewer_role=?,avatar_path=?,title=?,review_text=?,rating=?,status=?,sort_order=? WHERE id=?')->execute([...$data,$id]);else$pdo->prepare("INSERT INTO testimonials(reviewer_name,reviewer_email,reviewer_role,avatar_path,title,review_text,rating,status,sort_order,source) VALUES(?,?,?,?,?,?,?,?,?,\'admin\')")->execute($data);$this->go('Review saved.');}
 private function upload(?array $file):?string{if(!$file||($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;if(($file['error']??1)!==UPLOAD_ERR_OK||(int)($file['size']??0)>3*1024*1024)throw new \RuntimeException('Upload a profile image smaller than 3MB.');$info=@getimagesize((string)$file['tmp_name']);$types=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($types[$info['mime']??'']))throw new \RuntimeException('Use a JPG, PNG or WebP profile image.');$dir=BASE_PATH.'/public/assets/uploads/testimonials';if(!is_dir($dir))mkdir($dir,0775,true);$name=bin2hex(random_bytes(16)).'.'.$types[$info['mime']];if(!move_uploaded_file((string)$file['tmp_name'],$dir.'/'.$name))throw new \RuntimeException('Profile image upload failed.');return '/assets/uploads/testimonials/'.$name;}
 private function go(string $message,string $type='success',?int $id=null):never{$_SESSION['review_admin_flash']=compact('message','type');header('Location: /admin/reviews'.($id?'?edit='.$id:''),true,303);exit;}
}
