<section class="mx-auto w-full max-w-6xl py-10 sm:py-14">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-primary">Your selection</p><h1 class="mt-2 text-3xl font-black text-secondary">Shopping cart</h1><p class="mt-2 text-sm text-secondary/60">Review quantities before continuing to checkout.</p></div><a href="/shop" class="rounded-xl border border-primary/20 px-4 py-2.5 text-sm font-bold text-primary hover:bg-primary/5">Continue shopping</a></div>
    <div id="cart-empty" class="mt-8 hidden rounded-3xl border border-dashed border-primary/20 bg-primary/5 px-6 py-16 text-center"><iconify-icon icon="heroicons:shopping-cart" width="42" height="42" class="text-primary"></iconify-icon><h2 class="mt-4 text-xl font-black text-secondary">Your cart is empty</h2><p class="mt-2 text-sm text-secondary/60">Add a thoughtful gift to see it here.</p><a href="/shop" class="mt-6 inline-flex rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white hover:bg-secondary">Browse gifts</a></div>
    <div id="cart-content" class="mt-8 grid gap-6 lg:grid-cols-[1fr_20rem]">
        <div id="cart-items" class="space-y-4"></div>
        <aside><div class="sticky top-24 rounded-3xl border border-primary/10 bg-white p-6 shadow-lg"><h2 class="text-lg font-black text-secondary">Selected summary</h2><div class="mt-5 flex justify-between border-t border-primary/10 pt-5 text-lg font-black text-secondary"><span>Total</span><span id="cart-total">LKR 0.00</span></div><button id="buy-selected" type="button" class="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white hover:bg-secondary">Buy selected products</button><p class="mt-3 text-xs leading-5 text-secondary/55">Tick one or more products. You can also use Buy now for a single product.</p><button id="clear-cart" type="button" class="mt-4 w-full rounded-xl border border-accent/30 px-4 py-2.5 text-sm font-bold text-accent hover:bg-accent/10">Clear cart</button></div></aside>
    </div>
</section>
<script>
(function(){
    var items=document.getElementById('cart-items'),empty=document.getElementById('cart-empty'),content=document.getElementById('cart-content'),total=document.getElementById('cart-total');
    function cart(){try{return JSON.parse(localStorage.getItem('giftvibe_cart')||'[]');}catch(error){return [];}}
    function save(value){localStorage.setItem('giftvibe_cart',JSON.stringify(value));if(window.updateCartUI)window.updateCartUI();render();}
    function money(value){return 'LKR '+Number(value||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2});}
    function escape(value){var element=document.createElement('div');element.textContent=String(value||'');return element.innerHTML;}
    function render(){var value=cart();empty.classList.toggle('hidden',value.length>0);content.classList.toggle('hidden',value.length===0);items.innerHTML='';value.forEach(function(item,index){var quantity=Math.max(1,Number(item.qty)||1),price=Number(item.price)||0;var row=document.createElement('article');row.className='flex flex-col gap-4 rounded-2xl border border-primary/10 bg-white p-4 shadow-sm sm:flex-row sm:items-center';row.innerHTML='<label class="flex items-center"><input type="checkbox" data-select="'+index+'" checked class="h-5 w-5 accent-primary" aria-label="Select '+escape(item.name)+'"></label><img src="'+escape(item.image||'/assets/images/logo.svg')+'" alt="" class="h-24 w-24 rounded-xl bg-primary/5 object-cover"><div class="min-w-0 flex-1"><h2 class="truncate font-bold text-secondary">'+escape(item.name)+'</h2><p class="mt-1 text-sm text-secondary/60">'+money(price)+' each</p><p class="mt-2 font-black text-primary">'+money(price*quantity)+'</p></div><div class="flex items-center gap-2"><button type="button" data-change="-1" data-index="'+index+'" class="flex h-9 w-9 items-center justify-center rounded-lg border border-primary/20 text-secondary hover:bg-primary/5">−</button><span class="w-8 text-center text-sm font-black text-secondary">'+quantity+'</span><button type="button" data-change="1" data-index="'+index+'" class="flex h-9 w-9 items-center justify-center rounded-lg border border-primary/20 text-secondary hover:bg-primary/5">+</button></div><div class="flex gap-2"><button type="button" data-buy="'+index+'" class="rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-white hover:bg-secondary">Buy now</button><button type="button" data-remove="'+index+'" class="rounded-lg border border-accent/30 px-3 py-2.5 text-xs font-bold text-accent hover:bg-accent/10" aria-label="Remove item"><iconify-icon icon="heroicons:trash-solid" width="16" height="16"></iconify-icon></button></div>';items.appendChild(row);});updateSelectedTotal();}
    function selectedItems(){var value=cart();return Array.from(items.querySelectorAll('[data-select]:checked')).map(function(input){return value[Number(input.dataset.select)];}).filter(Boolean);}
    function updateSelectedTotal(){total.textContent=money(selectedItems().reduce(function(sum,item){return sum+(Number(item.price)||0)*Math.max(1,Number(item.qty)||1);},0));}
    items.addEventListener('click',function(event){var change=event.target.closest('[data-change]'),remove=event.target.closest('[data-remove]'),buy=event.target.closest('[data-buy]'),value=cart();if(change){var index=Number(change.dataset.index);value[index].qty=Math.max(1,(Number(value[index].qty)||1)+Number(change.dataset.change));save(value);}if(remove){value.splice(Number(remove.dataset.remove),1);save(value);}if(buy){var item=value[Number(buy.dataset.buy)];window.giftRequireAuth('/checkout?product='+encodeURIComponent(item.slug)+'&qty='+Math.max(1,Number(item.qty)||1));}});
    items.addEventListener('change',function(event){if(event.target.matches('[data-select]'))updateSelectedTotal();});
    document.getElementById('buy-selected').addEventListener('click',function(){var selected=selectedItems();if(!selected.length){window.GiftVibeToast.show('Select at least one product.','error');return;}var token=selected.map(function(item){return ((item.type||'product')==='combo'?'c~':'p~')+encodeURIComponent(item.slug)+':'+Math.max(1,Number(item.qty)||1);}).join(',');window.giftRequireAuth('/checkout?items='+token);});
    document.getElementById('clear-cart').addEventListener('click',function(){save([]);});
    render();
})();
</script>
