<?php declare(strict_types=1);
$input=static function($n,$l,$v='',$t='text',$p=''){$inputName=$n;$inputId=$n;$inputLabel=$l;$inputValue=(string)$v;$inputType=$t;$inputPlaceholder=$p;$inputHint='';$inputError='';$inputSize='lg';$inputState='default';$inputRequired=in_array($n,['reviewer_name'],true);$inputAutocomplete='';$inputReadonly=false;$inputDisabled=false;$inputLeadingIcon='';$inputPrefix='';$inputTrailingIcon='';$inputSuffix='';$inputAttributes=[];$inputClass='';$inputWrapperClass='';require BASE_PATH.'/resources/views/components/base/input.php';};
$button=static function($label,$options=[]){$buttonLabel=$label;$buttonVariant=$options['variant']??'solid';$buttonColor=$options['color']??'primary';$buttonSize=$options['size']??'md';$buttonType=$options['type']??'button';$buttonHref=$options['href']??'';$buttonName=$options['name']??'';$buttonValue=$options['value']??'';$buttonId='';$buttonIcon='';$buttonIconTrailing='';$buttonIconOnly=false;$buttonFullWidth=false;$buttonDisabled=false;$buttonLoading=false;$buttonOnclick='';$buttonClass='';$buttonAttributes=$options['attributes']??[];require BASE_PATH.'/resources/views/components/base/button.php';};?>
<div class="space-y-5"><?php if($flash):?><div class="rounded-xl px-4 py-3 text-sm <?=$flash['type']==='error'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'?>"><?=htmlspecialchars($flash['message'])?></div><?php endif;?><div class="flex items-center justify-between rounded-2xl border border-primary/10 bg-white p-5 shadow-sm"><div><h1 class="text-xl font-bold text-secondary">Customer reviews</h1><p class="mt-1 text-sm text-slate-500">Approve public submissions and manage homepage testimonials.</p></div><?php $button('Add review',['size'=>'lg','attributes'=>['data-drawer-open'=>'review-drawer']]);?></div>
<?php $rows=[];foreach($reviews as $r){
    $rid = (int)$r['id'];
    $editButton = '<a href="/admin/reviews?edit=' . $rid . '" title="View review" aria-label="View review" class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-primary/10 bg-white text-slate-500 transition hover:border-primary/20 hover:bg-primary/5 hover:text-primary">'
        . '<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12s3.75-6.75 9.75-6.75S21.75 12 21.75 12 18 18.75 12 18.75 2.25 12 2.25 12Z"/><circle cx="12" cy="12" r="2.25"/></svg></a>';
    $deleteButton = '<form method="post" class="inline-flex" onsubmit="return confirm(\'Delete review?\')">'
        . '<input type="hidden" name="csrf_token" value="' . htmlspecialchars($csrfToken) . '">'
        . '<input type="hidden" name="id" value="' . $rid . '">'
        . '<button type="submit" name="action" value="delete" title="Delete review" aria-label="Delete review" class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-rose-200 bg-white text-rose-500 transition hover:bg-rose-50 hover:text-rose-600">'
        . '<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166M19.228 5.79 18.16 19.673A2.25 2.25 0 0 1 15.916 21H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .563c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0V4.477c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"/></svg></button></form>';
    
    $rows[]=['reviewer'=>'<strong class="text-secondary">'.htmlspecialchars($r['reviewer_name']).'</strong><small class="block text-slate-400">'.htmlspecialchars($r['source']).'</small>','review'=>htmlspecialchars(mb_strimwidth($r['review_text'],0,100,'…')),'rating'=>str_repeat('★',(int)$r['rating']),'status'=>'<span class="rounded-full px-2.5 py-1 text-xs font-bold '.($r['status']==='approved'?'bg-emerald-50 text-emerald-700':($r['status']==='pending'?'bg-amber-50 text-amber-700':'bg-rose-50 text-rose-700')).'">'.ucfirst($r['status']).'</span>','_actions'=>'<div class="flex justify-end gap-2">'.$editButton.$deleteButton.'</div>'];
}
$tableId='reviews-table';$tableRows=$rows;$tableColumns=[['key'=>'reviewer','label'=>'Reviewer','html'=>true],['key'=>'review','label'=>'Review'],['key'=>'rating','label'=>'Rating'],['key'=>'status','label'=>'Status','html'=>true],['key'=>'_actions','label'=>'Action','html'=>true,'sortable'=>false,'align'=>'right']];$tablePerPage=10;$tableZebra=false;$tableEmptyMessage='No reviews found.';require BASE_PATH.'/resources/views/components/base/datatable.php';?></div>
<?php ob_start();?><form id="review-form" method="post" enctype="multipart/form-data" class="space-y-5"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><?php if($edit):?><input type="hidden" name="id" value="<?=(int)$edit['id']?>"><?php endif;?><?php $input('reviewer_name','Reviewer name',$edit['reviewer_name']??'');?><div class="grid gap-4 sm:grid-cols-2"><?php $input('reviewer_email','Email',$edit['reviewer_email']??'','email');$input('reviewer_role','Role / location',$edit['reviewer_role']??'','','Colombo, Sri Lanka');?></div>

<?php 
$fileName = 'avatar';
$fileId = 'reviewer-avatar';
$fileLabel = 'Profile Image (Avatar)';
$fileHint = 'JPG, PNG or WebP · maximum 5MB';
$fileAccept = 'image/png,image/jpeg,image/webp';
$fileRequired = false;
$fileCurrentUrl = !empty($edit['avatar_path']) ? htmlspecialchars($edit['avatar_path']) : '';
$fileMultiple = false;
require BASE_PATH . '/resources/views/components/base/file-input.php';
?>

<?php $input('title','Review title',$edit['title']??'');?><label class="block space-y-1.5"><span class="text-sm font-medium text-secondary">Review *</span><textarea required name="review_text" rows="5" class="w-full rounded-xl border border-primary/10 bg-white p-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"><?=htmlspecialchars((string)($edit['review_text']??''))?></textarea></label><div class="grid gap-4 sm:grid-cols-3 font-semibold"><?php $selectName='rating';$selectId='review-rating';$selectOptions=['5'=>'5 stars','4'=>'4 stars','3'=>'3 stars','2'=>'2 stars','1'=>'1 star'];$selectValue=(string)($edit['rating']??5);$selectPlaceholder='Rating';$selectLabel='Rating';$selectHint='';$selectError='';$selectSize='lg';$selectState='default';$selectMultiple=false;$selectRequired=true;$selectDisabled=false;$selectAttributes=[];$selectClass='';require BASE_PATH.'/resources/views/components/base/select.php';$selectName='status';$selectId='review-status';$selectOptions=['pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected'];$selectValue=(string)($edit['status']??'approved');$selectPlaceholder='Status';$selectLabel='Status';require BASE_PATH.'/resources/views/components/base/select.php';$input('sort_order','Order',$edit['sort_order']??0,'number');?></div></form><?php $drawerBody=ob_get_clean();ob_start();$button('Cancel',['variant'=>'outline','color'=>'secondary','size'=>'lg','attributes'=>['data-drawer-close'=>'']]);$button($edit?'Update review':'Create review',['type'=>'submit','size'=>'lg','attributes'=>['form'=>'review-form']]);$drawerFooter=ob_get_clean();$drawerId='review-drawer';$drawerSide='right';$drawerSize='lg';$drawerTitle=$edit?'View & edit review':'Add review';$drawerDescription='Only approved reviews appear on the homepage.';$drawerTrigger='<span class="hidden"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;require BASE_PATH.'/resources/views/components/base/drawer.php';?><?php if($edit):?><script>document.addEventListener('DOMContentLoaded',()=>document.querySelector('[data-drawer-open="review-drawer"]')?.click())</script><?php endif;?>
