<?php declare(strict_types=1); ?>
<div id="gv-step-2" data-step-panel="2" class="hidden space-y-5">
 <div class="grid min-h-[26rem] gap-5 lg:grid-cols-[1.15fr_0.85fr]">
  <div class="rounded-2xl border border-slate-200 bg-white p-4"><div class="mb-4"><h4 class="text-sm font-bold text-secondary">Choose products</h4><p class="mt-1 text-xs text-slate-500">Search and click a product card to add it.</p></div>
   <?php $inputName='combo_product_search';$inputId='combo-product-search';$inputLabel='';$inputValue='';$inputType='search';$inputPlaceholder='Search products by name or SKU...';$inputHint=$inputError='';$inputSize='lg';$inputState='default';$inputRequired=$inputReadonly=$inputDisabled=false;$inputAutocomplete='off';$inputLeadingIcon='<svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="m20 20-3.5-3.5M18 10.5a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/></svg>';$inputPrefix=$inputTrailingIcon=$inputSuffix='';$inputAttributes=[];$inputClass=$inputWrapperClass='w-full';require BASE_PATH.'/resources/views/components/base/input.php'; ?>
   <div id="combo-product-catalog" class="mt-4 grid max-h-[28rem] gap-2 overflow-y-auto pr-1 sm:grid-cols-2"></div>
  </div>
  <div class="rounded-2xl border border-slate-200 bg-slate-50/50 p-4"><div class="mb-4 flex items-center justify-between"><div><h4 class="text-sm font-bold text-secondary">Selected products</h4><p class="mt-1 text-xs text-slate-500">Remove products you do not need.</p></div><span id="combo-selected-count" class="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">0</span></div><div id="combo-selected-products" class="space-y-2"></div></div>
 </div>
 <div class="rounded-2xl border border-slate-200 bg-white p-5"><h4 class="text-sm font-bold text-secondary">Pricing calculation</h4>
  <div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-blue-50 p-3"><p class="text-[10px] font-bold uppercase text-blue-600">Buying price</p><p id="combo-total-cost" class="mt-1 font-bold text-blue-700">LKR 0.00</p></div><div class="rounded-xl bg-amber-50 p-3"><p class="text-[10px] font-bold uppercase text-amber-700">Final cost</p><p id="combo-total-final-cost" class="mt-1 font-bold text-amber-800">LKR 0.00</p></div><div class="rounded-xl bg-purple-50 p-3"><p class="text-[10px] font-bold uppercase text-purple-600">Products total</p><p id="combo-total-selling" class="mt-1 font-bold text-purple-700">LKR 0.00</p></div></div>
  <div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="block"><span class="mb-1.5 block text-xs font-bold text-secondary">Other cost</span><input id="field-other-cost" type="number" min="0" step="0.01" name="other_cost" value="<?= htmlspecialchars((string)($editCombo['other_cost']??'0.00')) ?>" class="<?= $fc ?>"></label><label class="block"><span class="mb-1.5 block text-xs font-bold text-secondary">Combo selling price <span class="text-primary">*</span></span><input id="field-price" required type="number" min="0.01" step="0.01" name="price" value="<?= htmlspecialchars((string)($editCombo['price']??'')) ?>" class="<?= $fc ?>"></label></div>
  <div class="mt-4 rounded-xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-400">Calculated profit</p><p id="combo-profit-display" class="mt-1 text-2xl font-black text-slate-300">LKR 0.00</p></div>
 </div>
</div>
<script>(function(){
var products=<?= json_encode(array_values(array_map(static fn(array $p):array=>['id'=>(int)$p['id'],'name'=>(string)$p['name'],'sku'=>(string)$p['sku'],'price'=>(float)$p['base_price'],'image'=>(string)($p['image_path']??'')],$products)),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>,selected=new Set(<?= json_encode(array_values(array_map('intval',$selectedProducts))) ?>),catalog=document.getElementById('combo-product-catalog'),chosen=document.getElementById('combo-selected-products'),search=document.getElementById('combo-product-search');
function esc(v){var d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}function money(v){return'LKR '+Number(v||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}
function drawCatalog(){var q=(search?.value||'').trim().toLowerCase(),rows=products.filter(function(p){return!selected.has(p.id)&&(!q||p.name.toLowerCase().includes(q)||p.sku.toLowerCase().includes(q))}).slice(0,20);catalog.innerHTML=rows.length?rows.map(function(p){return'<button type="button" data-combo-add="'+p.id+'" class="group flex min-h-[82px] items-center gap-3 rounded-xl border border-slate-200 bg-white p-2.5 text-left shadow-sm transition hover:border-primary/40"><img src="'+esc(p.image)+'" alt="'+esc(p.name)+'" class="h-16 w-16 shrink-0 rounded-lg object-cover"><span class="min-w-0 flex-1"><span class="line-clamp-2 block text-sm font-bold text-secondary group-hover:text-primary">'+esc(p.name)+'</span><span class="mt-1 block text-sm font-black text-primary">'+money(p.price)+'</span></span></button>'}).join(''):'<p class="col-span-full py-10 text-center text-sm text-slate-400">No products found.</p>'}
function drawSelected(){var rows=products.filter(function(p){return selected.has(p.id)});document.getElementById('combo-selected-count').textContent=String(rows.length);chosen.innerHTML=rows.length?rows.map(function(p){return'<div class="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-2.5"><img src="'+esc(p.image)+'" class="h-12 w-12 rounded-lg object-cover" alt=""><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold text-secondary">'+esc(p.name)+'</p><p class="text-xs font-bold text-primary">'+money(p.price)+'</p></div><input type="hidden" name="product_ids[]" value="'+p.id+'"><button type="button" data-combo-remove="'+p.id+'" class="h-8 w-8 rounded-lg border border-rose-100 text-rose-600 hover:bg-rose-50">&times;</button></div>'}).join(''):'<div class="rounded-xl border border-dashed border-slate-200 py-12 text-center text-sm text-slate-400">No products selected.</div>';document.dispatchEvent(new CustomEvent('combo:products-change'))}
document.addEventListener('click',function(e){var a=e.target.closest('[data-combo-add]'),r=e.target.closest('[data-combo-remove]');if(a){selected.add(Number(a.dataset.comboAdd));drawCatalog();drawSelected()}if(r){selected.delete(Number(r.dataset.comboRemove));drawCatalog();drawSelected()}});search?.addEventListener('input',drawCatalog);drawCatalog();drawSelected();})();</script>
