<?php declare(strict_types=1);
if(!$viewItem)return;
$batchLabel=static function(int $number):string{$label='';while($number>0){$number--;$label=chr(65+($number%26)).$label;$number=intdiv($number,26);}return $label;};
ob_start(); ?>
<div class="space-y-4">
    <div class="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50 p-5"><div><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Item</p><h3 class="mt-1 text-xl font-black text-secondary"><?=htmlspecialchars((string)$viewItem['name'])?></h3></div><div class="text-right"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Total stock</p><p class="mt-1 text-2xl font-black text-primary"><?=number_format((int)$viewItem['quantity'])?></p></div></div>
    <details open class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><summary class="flex cursor-pointer list-none items-center justify-between px-5 py-4 font-bold text-secondary"><span>Current inventory</span><span>⌄</span></summary><div class="grid gap-3 border-t border-slate-200 p-5 sm:grid-cols-2"><div class="rounded-xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-400">Product cost</p><p class="mt-1 font-black text-secondary">LKR <?=number_format((float)$viewItem['cost_price'],2)?></p></div><div class="rounded-xl bg-slate-50 p-4"><p class="text-[10px] font-bold uppercase text-slate-400">Number of stock</p><p class="mt-1 font-black text-secondary"><?=number_format((int)$viewItem['quantity'])?></p></div></div></details>
    <details open class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><summary class="flex cursor-pointer list-none items-center justify-between px-5 py-4 font-bold text-secondary"><span>Stock batches (<?=count($viewBatches)?>)</span><span>⌄</span></summary><div class="space-y-3 border-t border-slate-200 p-5">
        <?php foreach($viewBatches as $index=>$batch): $number=count($viewBatches)-$index;?>
        <div class="rounded-xl border border-slate-200 p-4">
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p class="text-[10px] font-bold uppercase text-slate-400">Batch</p><p class="mt-1 font-bold text-primary"><?=$batchLabel($number)?></p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Cost</p><p class="mt-1 font-bold text-secondary">LKR <?=number_format((float)$batch['unit_cost'],2)?></p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Received</p><p class="mt-1 font-bold text-secondary"><?=(int)$batch['quantity_received']?></p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Date</p><p class="mt-1 text-xs font-semibold text-secondary"><?=htmlspecialchars(date('Y-m-d',strtotime((string)$batch['received_at'])))?></p></div></div>
            <div class="mt-4 flex items-end gap-2 border-t border-slate-100 pt-4"><form method="post" action="/admin/inventory" class="flex flex-1 items-end gap-2"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><input type="hidden" name="action" value="update_batch"><input type="hidden" name="batch_id" value="<?=(int)$batch['id']?>"><input type="hidden" name="inventory_item_id" value="<?=(int)$viewItem['id']?>"><label class="flex-1"><span class="mb-1 block text-[10px] font-bold uppercase text-slate-400">Remaining stock</span><input type="number" min="0" step="1" name="quantity_remaining" value="<?=(int)$batch['quantity_remaining']?>" class="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold text-secondary outline-none focus:border-primary"></label><button type="submit" title="Save batch stock" class="inline-flex h-10 w-10 items-center justify-center rounded-lg border border-primary/15 text-primary hover:bg-primary/5"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5.25 3.75h11.086a1.5 1.5 0 0 1 1.06.44l2.414 2.414a1.5 1.5 0 0 1 .44 1.06V18.75a1.5 1.5 0 0 1-1.5 1.5H5.25a1.5 1.5 0 0 1-1.5-1.5V5.25a1.5 1.5 0 0 1 1.5-1.5Z"/><path d="M8.25 3.75v5.5h7.5v-5.5M8.25 20.25v-6.5h7.5v6.5"/></svg></button></form><form method="post" action="/admin/inventory" onsubmit="return confirm('Delete this stock batch?')"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><input type="hidden" name="action" value="delete_batch"><input type="hidden" name="batch_id" value="<?=(int)$batch['id']?>"><input type="hidden" name="inventory_item_id" value="<?=(int)$viewItem['id']?>"><button type="submit" title="Delete batch" class="inline-flex h-10 w-10 items-center justify-center rounded-lg border border-rose-200 text-rose-500 hover:bg-rose-50"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0H4.772"/></svg></button></form></div>
        </div>
        <?php endforeach;?>
        <?php if(!$viewBatches):?><p class="py-8 text-center text-sm text-slate-400">No stock batches recorded.</p><?php endif;?>
    </div></details>
</div>
<?php
$editUrl=app_url('/admin/inventory?edit='.(int)$viewItem['id']);
$drawerBody=(string)ob_get_clean();$drawerFooter='<button type="button" data-drawer-close class="rounded-xl border border-slate-200 px-6 py-2.5 text-sm font-bold text-secondary hover:bg-slate-50">Close</button><a href="'.htmlspecialchars($editUrl,ENT_QUOTES).'" class="inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-2.5 text-sm font-bold text-white hover:bg-secondary"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Z"/></svg>Edit</a>';$drawerId='inventory-view-drawer';$drawerSide='right';$drawerSize='xl';$drawerTitle=(string)$viewItem['name'];$drawerDescription='Inventory details and purchase batches.';$drawerTrigger='<button type="button" data-drawer-open="inventory-view-drawer" class="hidden" data-inventory-view-trigger tabindex="-1"></button>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;$drawerHeaderBottom='';require BASE_PATH.'/resources/views/components/base/drawer.php';
?>
<script>document.addEventListener('DOMContentLoaded',function(){document.querySelector('[data-inventory-view-trigger]')?.click();});</script>
