<?php declare(strict_types=1); ?>
<div class="space-y-5">
    <div class="rounded-2xl border border-primary/10 bg-white p-5 shadow-sm"><h1 class="text-xl font-bold text-secondary">Order verification</h1><p class="mt-1 text-sm text-secondary/60">Review receipts, confirm delivery timing, or cancel an order.</p></div>
    <?php if ($flash): ?><span class="hidden" data-toast-message="<?= htmlspecialchars((string)$flash['message'], ENT_QUOTES) ?>" data-toast-type="<?= htmlspecialchars((string)$flash['type'], ENT_QUOTES) ?>"></span><?php endif; ?>
    <?php if (!$orders): ?><div class="rounded-2xl border border-dashed border-primary/20 p-12 text-center text-sm text-secondary/60">No orders have been placed yet.</div><?php endif; ?>
    <div class="grid gap-5"><?php foreach ($orders as $order): $paymentMeta = json_decode((string) ($order['raw_response_json'] ?? ''), true) ?: []; ?>
        <article class="rounded-2xl border border-primary/10 bg-white p-5 shadow-sm">
            <div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex items-center gap-2"><h2 class="font-black text-secondary"><?= htmlspecialchars($order['order_number']) ?></h2><span class="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary"><?= htmlspecialchars(ucfirst($order['order_status'])) ?></span></div><p class="mt-1 text-sm text-secondary/60"><?= htmlspecialchars($order['customer_name']) ?> · <?= htmlspecialchars($order['customer_phone']) ?> · <?= htmlspecialchars($order['customer_email']) ?></p></div><div class="text-right"><p class="font-black text-secondary">LKR <?= number_format((float) $order['grand_total'], 2) ?></p><p class="text-xs text-secondary/60"><?= htmlspecialchars(str_replace('_', ' ', ucfirst($order['method'] ?? ''))) ?> · receipt LKR <?= number_format((float) ($order['payment_amount'] ?? 0), 2) ?></p></div></div>
            <div class="mt-4 grid gap-4 rounded-xl bg-primary/5 p-4 text-sm text-secondary sm:grid-cols-3"><div><p class="font-bold">Deliver to</p><p class="mt-1 text-secondary/70"><?= htmlspecialchars($order['recipient_name']) ?>, <?= htmlspecialchars($order['recipient_phone']) ?><br><?= htmlspecialchars($order['delivery_address_line_1'] . ', ' . $order['delivery_city'] . ', ' . $order['delivery_district']) ?></p></div><div><p class="font-bold">Payment option</p><p class="mt-1 text-secondary/70"><?= htmlspecialchars(ucfirst($paymentMeta['payment_option'] ?? '')) ?><br>Balance: LKR <?= number_format((float) ($paymentMeta['balance_due'] ?? 0), 2) ?></p></div><div><p class="font-bold">Receipt</p><?php if ($order['receipt_path']): ?><a target="_blank" rel="noopener" href="<?= htmlspecialchars($order['receipt_path']) ?>" class="mt-1 inline-flex font-bold text-primary underline">Open uploaded receipt</a><?php else: ?><p class="mt-1 text-accent">Missing</p><?php endif; ?></div></div>
            <?php if ($order['order_status'] === 'pending'): ?><form method="post" class="mt-4 grid gap-3 sm:grid-cols-[9rem_1fr_auto_auto]"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="order_id" value="<?= (int) $order['id'] ?>"><label class="text-xs font-bold text-secondary">Delivery days<input required type="number" name="delivery_days" min="1" max="30" value="3" class="mt-1 w-full rounded-lg border border-primary/20 px-3 py-2 text-sm outline-none focus:border-primary"></label><label class="text-xs font-bold text-secondary">Admin note<input name="admin_notes" class="mt-1 w-full rounded-lg border border-primary/20 px-3 py-2 text-sm outline-none focus:border-primary" placeholder="Optional reason or delivery note"></label><button name="decision" value="confirm" data-confirm="Confirm this order and notify the customer?" class="self-end rounded-lg bg-primary px-4 py-2 text-sm font-bold text-white hover:bg-secondary">Confirm</button><button name="decision" value="cancel" data-confirm="Cancel this order and notify the customer?" class="self-end rounded-lg border border-accent px-4 py-2 text-sm font-bold text-accent hover:bg-accent hover:text-white">Cancel</button></form><?php elseif ($order['delivery_date']): ?><p class="mt-4 text-sm font-semibold text-primary">Expected delivery: <?= htmlspecialchars($order['delivery_date']) ?></p><?php endif; ?>
        </article>
    <?php endforeach; ?></div>
</div>
