<?php
declare(strict_types=1);
$fieldClass='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-secondary outline-none focus:border-primary focus:ring-2 focus:ring-primary/10';
$tableRows=[];
foreach ($products as $item) {
 $id=(int)$item['id']; $img=(string)($item['image_path'] ?? '/assets/images/hero_slide_1.jpg'); if(str_starts_with($img,'public/'))$img='/'.substr($img,7);
 $active=$item['status']==='active';
 $actions='<div class="flex items-center justify-end gap-2"><a href="/admin/products?edit='.$id.'" title="View product" class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:text-primary"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.25 12s3.75-6.75 9.75-6.75S21.75 12 21.75 12 18 18.75 12 18.75 2.25 12 2.25 12Z"/><circle cx="12" cy="12" r="2.25"/></svg></a><form method="post" action="/admin/products" onsubmit="return confirm(\'Delete this product?\')"><input type="hidden" name="csrf_token" value="'.htmlspecialchars($csrfToken,ENT_QUOTES).'"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="'.$id.'"><button class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-rose-200 text-rose-500 hover:bg-rose-50" title="Delete">&times;</button></form></div>';
 $tableRows[]=['product'=>'<div class="flex min-w-64 items-center gap-3"><img src="'.htmlspecialchars($img,ENT_QUOTES).'" class="h-14 w-16 rounded-lg object-cover"><div><p class="font-semibold text-secondary">'.htmlspecialchars($item['name']).'</p><p class="text-xs text-slate-500">'.htmlspecialchars($item['sku']).' · '.htmlspecialchars((string)$item['category_names']).'</p></div></div>','price'=>'LKR '.number_format((float)$item['base_price'],2),'stock'=>(int)$item['stock_quantity'],'status'=>$active?'<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Active</span>':'<span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500">Draft</span>','_actions'=>$actions];
}
$editImage=(string)($editProduct['image_path'] ?? ''); if(str_starts_with($editImage,'public/'))$editImage='/'.substr($editImage,7);
?>
<div class="space-y-5">
 <?php if($flash):?><div class="rounded-xl px-4 py-3 text-sm <?= $flash['type']==='error'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700' ?>"><?=htmlspecialchars($flash['message'])?></div><?php endif;?>
 <div class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-xl font-bold text-secondary">Products</h1><p class="mt-1 text-sm text-slate-500">Manage products and assign them to categories.</p></div><button type="button" data-drawer-open="product-drawer" class="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">+ Add product</button></div>
 <div class="flex gap-3"><input type="search" data-datatable-search data-datatable-target="products-table" placeholder="Search products..." class="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm outline-none"><button data-datatable-reset data-datatable-target="products-table" class="rounded-xl border border-slate-200 px-4 text-sm font-semibold">Reset</button></div>
 <?php $tableId='products-table';$tableColumns=[['key'=>'product','label'=>'Product','html'=>true,'sortable'=>false],['key'=>'price','label'=>'Price'],['key'=>'stock','label'=>'Stock','type'=>'number'],['key'=>'status','label'=>'Status','html'=>true,'sortable'=>false],['key'=>'_actions','label'=>'Action','html'=>true,'sortable'=>false,'align'=>'right']];$tableSortable=true;$tableDefaultSort=null;$tablePaginated=true;$tablePerPage=10;$tableZebra=false;$tableEmptyMessage='No products found.';require BASE_PATH.'/resources/views/components/base/datatable.php';?>
</div>
<?php ob_start(); ?>
<form id="product-form" method="post" action="/admin/products" enctype="multipart/form-data" class="space-y-5"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><input type="hidden" name="action" value="save"><?php if($editProduct):?><input type="hidden" name="id" value="<?=(int)$editProduct['id']?>"><?php endif;?>
 <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-xs font-semibold">Product name *</span><input required name="name" value="<?=htmlspecialchars((string)($editProduct['name']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">SKU *</span><input required name="sku" value="<?=htmlspecialchars((string)($editProduct['sku']??''))?>" class="<?=$fieldClass?>"></label></div>
 <label class="block"><span class="mb-1.5 block text-xs font-semibold">Short description</span><textarea name="short_description" rows="2" class="<?=$fieldClass?>"><?=htmlspecialchars((string)($editProduct['short_description']??''))?></textarea></label>
 <label class="block"><span class="mb-1.5 block text-xs font-semibold">Full description</span><textarea name="description" rows="5" class="<?=$fieldClass?>" placeholder="Product contents and detailed gifting information"><?=htmlspecialchars((string)($editProduct['description']??''))?></textarea></label>
 <div class="rounded-2xl border border-blue-100 bg-blue-50/40 p-4">
  <p class="text-xs font-extrabold uppercase tracking-wider text-primary">SEO & AI discovery</p>
  <div class="mt-3 space-y-3">
   <label class="block"><span class="mb-1.5 block text-xs font-semibold">SEO title</span><input name="meta_title" maxlength="190" value="<?=htmlspecialchars((string)($editProduct['meta_title']??''))?>" placeholder="Leave empty to use product name" class="<?=$fieldClass?>"><span class="mt-1 block text-[11px] text-slate-400">Recommended: clear product name + gifting intent, under 60 characters.</span></label>
   <label class="block"><span class="mb-1.5 block text-xs font-semibold">SEO / GEO description</span><textarea name="meta_description" maxlength="255" rows="3" class="<?=$fieldClass?>" placeholder="Who this gift is for, what it contains, occasion and delivery value"><?=htmlspecialchars((string)($editProduct['meta_description']??''))?></textarea><span class="mt-1 block text-[11px] text-slate-400">Used by search engines, social previews and AI answer engines.</span></label>
  </div>
 </div>
 <?php $selectName='category_ids[]';$selectId='product-categories';$selectOptions=[];foreach($categories as $category)$selectOptions[(string)$category['id']]=$category['name'];$selectValue=array_map('strval',$editCategoryIds);$selectPlaceholder='Select product categories';$selectLabel='Categories';$selectHint='Select one or more categories for this product.';$selectError='';$selectSize='lg';$selectState='default';$selectMultiple=true;$selectRequired=true;$selectDisabled=false;$selectAttributes=[];$selectClass='';require BASE_PATH.'/resources/views/components/base/select.php';?>
  
  <label class="block"><span class="mb-1.5 block text-xs font-semibold">Image Alt Text (SEO)</span><input name="image_alt_text" value="<?=htmlspecialchars((string)($editProduct['alt_text']??''))?>" placeholder="e.g. Handmade Flower Bouquet" class="<?=$fieldClass?>"></label>
  <div class="space-y-2"><div class="flex items-center justify-between"><span class="text-xs font-semibold">YouTube / video reference links</span><button type="button" data-add-video class="rounded-lg border border-primary/20 px-3 py-1.5 text-xs font-bold text-primary hover:bg-primary/5">+ Add link</button></div><div data-video-list class="space-y-2"><?php foreach(($productVideos?:['']) as $video):?><div data-video-row class="flex gap-2"><input type="url" name="video_urls[]" value="<?=htmlspecialchars((string)$video)?>" placeholder="https://www.youtube.com/watch?v=..." class="<?=$fieldClass?>"><button type="button" data-remove-video class="shrink-0 rounded-xl border border-rose-200 px-3 text-rose-600 hover:bg-rose-50" aria-label="Remove video link">&times;</button></div><?php endforeach;?></div></div>

  <?php $fileName='product_images[]';$fileId='product-images';$fileLabel='Product images';$fileHint='Select one or more JPG, PNG or WebP images, each maximum 5MB';$fileAccept='image/png,image/jpeg,image/webp';$fileRequired=$editProduct===null;$fileCurrentUrl='';$fileMultiple=true;require BASE_PATH.'/resources/views/components/base/file-input.php';?>
  
  <?php if (!empty($secondaryImages)): ?>
      <div class="rounded-xl border border-slate-200 p-4">
          <span class="mb-3 block text-xs font-semibold text-secondary">Saved product images</span>
          <div class="grid grid-cols-3 gap-3">
              <?php foreach ($secondaryImages as $secImg): 
                  $imgPath = (string)$secImg['image_path'];
                  if(str_starts_with($imgPath,'public/')) $imgPath = '/'.substr($imgPath,7);
              ?>
                  <div class="relative group rounded-lg overflow-hidden border border-slate-100 aspect-square">
                      <img src="<?=htmlspecialchars($imgPath)?>" class="h-full w-full object-cover">
                      <label class="absolute inset-0 bg-slate-900/65 opacity-0 group-hover:opacity-100 flex items-center justify-center text-white cursor-pointer transition-opacity">
                          <input type="checkbox" name="delete_images[]" value="<?=(int)$secImg['id']?>" class="mr-1.5 accent-rose-600"> Remove
                      </label>
                  </div>
              <?php endforeach; ?>
          </div>
      </div>
  <?php endif; ?>

  <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-xs font-semibold">Selling price *</span><input id="selling-price" required type="number" min="0" step="0.01" name="selling_price" value="<?=htmlspecialchars((string)($editProduct['base_price']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">Buying price *</span><input id="buying-price" required type="number" min="0" step="0.01" name="buying_price" value="<?=htmlspecialchars((string)($editProduct['cost_price']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">Profit</span><input id="product-profit" readonly value="0.00" class="<?=$fieldClass?> bg-emerald-50 font-bold text-emerald-700"></label><label><span class="mb-1.5 block text-xs font-semibold">Stock</span><input type="number" min="0" name="stock_quantity" value="<?=(int)($editProduct['stock_quantity']??0)?>" class="<?=$fieldClass?>"></label></div>
  <div class="grid gap-3 sm:grid-cols-2"><label class="flex items-center justify-between rounded-xl border p-3 text-sm font-semibold">Featured<input type="checkbox" name="is_featured" value="1" <?=!empty($editProduct['is_featured'])?'checked':''?> class="accent-primary"></label><label class="flex items-center justify-between rounded-xl border p-3 text-sm font-semibold">Active<input type="checkbox" name="status" value="active" <?=!$editProduct||$editProduct['status']==='active'?'checked':''?> class="accent-primary"></label></div>
</form>
<script>document.addEventListener('DOMContentLoaded',function(){var selling=document.getElementById('selling-price'),buying=document.getElementById('buying-price'),profit=document.getElementById('product-profit');function calculateProfit(){profit.value=(Math.max(0,parseFloat(selling.value)||0)-Math.max(0,parseFloat(buying.value)||0)).toFixed(2);}selling?.addEventListener('input',calculateProfit);buying?.addEventListener('input',calculateProfit);calculateProfit();var list=document.querySelector('[data-video-list]');function bindRemove(button){button.addEventListener('click',function(){var rows=list.querySelectorAll('[data-video-row]');if(rows.length>1)button.closest('[data-video-row]').remove();else button.closest('[data-video-row]').querySelector('input').value='';});}list?.querySelectorAll('[data-remove-video]').forEach(bindRemove);document.querySelector('[data-add-video]')?.addEventListener('click',function(){var row=document.createElement('div');row.dataset.videoRow='';row.className='flex gap-2';row.innerHTML='<input type="url" name="video_urls[]" placeholder="https://www.youtube.com/watch?v=..." class="<?=$fieldClass?>"><button type="button" data-remove-video class="shrink-0 rounded-xl border border-rose-200 px-3 text-rose-600 hover:bg-rose-50" aria-label="Remove video link">&times;</button>';list.appendChild(row);bindRemove(row.querySelector('[data-remove-video]'));});});</script>
<?php $drawerBody=(string)ob_get_clean();$drawerFooter='<button type="button" data-drawer-close class="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" form="product-form" class="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white">'.($editProduct?'Update product':'Add product').'</button>';$drawerId='product-drawer';$drawerSide='right';$drawerSize='lg';$drawerTitle=$editProduct?'View & edit product':'Add product';$drawerDescription='Product details, category, image and pricing.';$drawerTrigger='<span class="hidden" aria-hidden="true"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;require BASE_PATH.'/resources/views/components/base/drawer.php';?>
<?php if($editProduct):?><script>document.addEventListener('DOMContentLoaded',function(){document.querySelector('[data-drawer-open="product-drawer"]')?.click();});</script><?php endif;?>
