<?php
declare(strict_types=1);
$fieldClass='w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-secondary outline-none focus:border-primary focus:ring-2 focus:ring-primary/10';
$tableRows=[];
foreach ($products as $item) {
 $id=(int)$item['id']; $img=(string)($item['image_path'] ?? '/assets/images/hero_slide_1.jpg'); if(str_starts_with($img,'public/'))$img='/'.substr($img,7);
 $active=$item['status']==='active';
 $actions='<div class="flex items-center justify-end gap-2"><a href="/admin/products?edit='.$id.'" title="View product" class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 hover:text-primary"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.25 12s3.75-6.75 9.75-6.75S21.75 12 21.75 12 18 18.75 12 18.75 2.25 12 2.25 12Z"/><circle cx="12" cy="12" r="2.25"/></svg></a><form method="post" action="/admin/products" onsubmit="return confirm(\'Delete this product?\')"><input type="hidden" name="csrf_token" value="'.htmlspecialchars($csrfToken,ENT_QUOTES).'"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="'.$id.'"><button class="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-rose-200 text-rose-500 hover:bg-rose-50" title="Delete">&times;</button></form></div>';
 $tableRows[]=['product'=>'<div class="flex min-w-64 items-center gap-3"><img src="'.htmlspecialchars($img,ENT_QUOTES).'" class="h-14 w-16 rounded-lg object-cover"><div><p class="font-semibold text-secondary">'.htmlspecialchars($item['name']).'</p><p class="text-xs text-slate-500">'.htmlspecialchars($item['sku']).' · '.htmlspecialchars((string)$item['category_names']).'</p></div></div>','price'=>'LKR '.number_format((float)($item['sale_price'] ?: $item['base_price']),2),'stock'=>(int)$item['stock_quantity'],'status'=>$active?'<span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Active</span>':'<span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500">Draft</span>','_actions'=>$actions];
}
$editImage=(string)($editProduct['image_path'] ?? ''); if(str_starts_with($editImage,'public/'))$editImage='/'.substr($editImage,7);
?>
<div class="space-y-5">
 <?php if($flash):?><div class="rounded-xl px-4 py-3 text-sm <?= $flash['type']==='error'?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700' ?>"><?=htmlspecialchars($flash['message'])?></div><?php endif;?>
 <div class="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-xl font-bold text-secondary">Products</h1><p class="mt-1 text-sm text-slate-500">Manage products and assign them to categories.</p></div><button data-drawer-open="product-drawer" class="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white">+ Add product</button></div>
 <div class="flex gap-3"><input type="search" data-datatable-search data-datatable-target="products-table" placeholder="Search products..." class="w-full rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm outline-none"><button data-datatable-reset data-datatable-target="products-table" class="rounded-xl border border-slate-200 px-4 text-sm font-semibold">Reset</button></div>
 <?php $tableId='products-table';$tableColumns=[['key'=>'product','label'=>'Product','html'=>true,'sortable'=>false],['key'=>'price','label'=>'Price'],['key'=>'stock','label'=>'Stock','type'=>'number'],['key'=>'status','label'=>'Status','html'=>true,'sortable'=>false],['key'=>'_actions','label'=>'Action','html'=>true,'sortable'=>false,'align'=>'right']];$tableSortable=true;$tableDefaultSort=null;$tablePaginated=true;$tablePerPage=10;$tableZebra=false;$tableEmptyMessage='No products found.';require BASE_PATH.'/resources/views/components/base/datatable.php';?>
</div>
<?php ob_start(); ?>
<form id="product-form" method="post" action="/admin/products" enctype="multipart/form-data" class="space-y-5"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><input type="hidden" name="action" value="save"><?php if($editProduct):?><input type="hidden" name="id" value="<?=(int)$editProduct['id']?>"><?php endif;?>
 <div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-xs font-semibold">Product name *</span><input required name="name" value="<?=htmlspecialchars((string)($editProduct['name']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">SKU *</span><input required name="sku" value="<?=htmlspecialchars((string)($editProduct['sku']??''))?>" class="<?=$fieldClass?>"></label></div>
 <label class="block"><span class="mb-1.5 block text-xs font-semibold">Short description</span><textarea name="short_description" rows="2" class="<?=$fieldClass?>"><?=htmlspecialchars((string)($editProduct['short_description']??''))?></textarea></label>
 <fieldset><legend class="mb-2 text-xs font-semibold">Categories *</legend><div class="grid grid-cols-2 gap-2 rounded-xl border border-slate-200 p-3"><?php foreach($categories as $category):?><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="category_ids[]" value="<?=(int)$category['id']?>" <?=in_array((int)$category['id'],$editCategoryIds,true)?'checked':''?> class="accent-primary"><?=htmlspecialchars($category['name'])?></label><?php endforeach;?></div></fieldset>
 <?php $fileName='product_image';$fileId='product-image';$fileLabel='Product image';$fileHint='JPG, PNG or WebP · maximum 5MB';$fileAccept='image/png,image/jpeg,image/webp';$fileRequired=$editProduct===null;$fileCurrentUrl=$editImage;require BASE_PATH.'/resources/views/components/base/file-input.php';?>
 <div class="grid gap-4 sm:grid-cols-3"><label><span class="mb-1.5 block text-xs font-semibold">Price *</span><input required type="number" min="0" step="0.01" name="base_price" value="<?=htmlspecialchars((string)($editProduct['base_price']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">Sale price</span><input type="number" min="0" step="0.01" name="sale_price" value="<?=htmlspecialchars((string)($editProduct['sale_price']??''))?>" class="<?=$fieldClass?>"></label><label><span class="mb-1.5 block text-xs font-semibold">Stock</span><input type="number" min="0" name="stock_quantity" value="<?=(int)($editProduct['stock_quantity']??0)?>" class="<?=$fieldClass?>"></label></div>
 <div class="grid gap-3 sm:grid-cols-2"><label class="flex items-center justify-between rounded-xl border p-3 text-sm font-semibold">Featured<input type="checkbox" name="is_featured" value="1" <?=!empty($editProduct['is_featured'])?'checked':''?> class="accent-primary"></label><label class="flex items-center justify-between rounded-xl border p-3 text-sm font-semibold">Active<input type="checkbox" name="status" value="active" <?=!$editProduct||$editProduct['status']==='active'?'checked':''?> class="accent-primary"></label></div>
</form>
<?php $drawerBody=(string)ob_get_clean();$drawerFooter='<button data-drawer-close class="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" form="product-form" class="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white">'.($editProduct?'Update product':'Add product').'</button>';$drawerId='product-drawer';$drawerSide='right';$drawerSize='lg';$drawerTitle=$editProduct?'View & edit product':'Add product';$drawerDescription='Product details, category, image and pricing.';$drawerTrigger='';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;require BASE_PATH.'/resources/views/components/base/drawer.php';?>
<?php if($editProduct):?><script>document.addEventListener('DOMContentLoaded',function(){document.querySelector('[data-drawer-open="product-drawer"]')?.click();});</script><?php endif;?>
