<?php declare(strict_types=1); ob_start(); ?>
<div class="space-y-5">
 <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
  <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Transaction</p><h4 id="finance-view-name" class="mt-2 text-2xl font-bold text-secondary"></h4><p id="finance-view-reference" class="mt-1 text-sm text-slate-500"></p></div><span id="finance-view-type" class="rounded-full px-3 py-1 text-xs font-bold"></span></div>
 </div>
 <div class="grid gap-4 sm:grid-cols-2">
  <div class="rounded-2xl border border-slate-200 p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Amount</p><p id="finance-view-amount" class="mt-2 text-xl font-black text-secondary"></p></div>
  <div class="rounded-2xl border border-slate-200 p-5"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Date</p><p id="finance-view-date" class="mt-2 text-lg font-bold text-secondary"></p></div>
 </div>
 <div id="finance-order-details" class="hidden rounded-2xl border border-slate-200 p-5"><h5 class="text-base font-bold text-secondary">Order breakdown</h5><div class="mt-4 grid gap-4 sm:grid-cols-3"><div><p class="text-xs font-bold uppercase text-slate-400">Sales</p><p id="finance-view-sales" class="mt-1 font-bold text-secondary"></p></div><div><p class="text-xs font-bold uppercase text-slate-400">Product cost</p><p id="finance-view-cost" class="mt-1 font-bold text-secondary"></p></div><div><p class="text-xs font-bold uppercase text-slate-400">Profit</p><p id="finance-view-profit" class="mt-1 font-bold text-primary"></p></div></div></div>
 <div id="finance-purchase-details" class="hidden rounded-2xl border border-slate-200 p-5"><h5 class="text-base font-bold text-secondary">Purchase breakdown</h5><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><p class="text-xs font-bold uppercase text-slate-400">Unit cost</p><p id="finance-view-unit-cost" class="mt-1 font-bold text-secondary"></p></div><div><p class="text-xs font-bold uppercase text-slate-400">Quantity</p><p id="finance-view-quantity" class="mt-1 font-bold text-secondary"></p></div></div></div>
</div>
<script>
document.addEventListener('click',function(e){var btn=e.target.closest('[data-finance-view]');if(!btn)return;var cell=btn.closest('tr')?.querySelector('td[data-key="_meta"]');if(!cell)return;var v;try{v=JSON.parse(cell.textContent.trim());}catch(err){return;}var money=function(n){return 'LKR '+Number(n||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2});};var order=v.kind==='order';document.getElementById('finance-view-name').textContent=v.name||'';document.getElementById('finance-view-reference').textContent=v.reference||'';document.getElementById('finance-view-date').textContent=v.date||'';document.getElementById('finance-view-amount').textContent=(order?'+ ':'− ')+money(v.amount);var type=document.getElementById('finance-view-type');type.textContent=order?'Order cash in':'Product cash out';type.className='rounded-full px-3 py-1 text-xs font-bold '+(order?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700');document.getElementById('finance-order-details').classList.toggle('hidden',!order);document.getElementById('finance-purchase-details').classList.toggle('hidden',order);if(order){document.getElementById('finance-view-sales').textContent=money(v.sales);document.getElementById('finance-view-cost').textContent=money(v.cost);document.getElementById('finance-view-profit').textContent=money(v.profit);}else{document.getElementById('finance-view-unit-cost').textContent=money(v.unit_cost);document.getElementById('finance-view-quantity').textContent=String(v.quantity||0);}});
</script>
<?php $drawerBody=(string)ob_get_clean();$drawerFooter='<button type="button" data-drawer-close class="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold text-secondary hover:bg-slate-50">Close</button>';$drawerId='finance-view-drawer';$drawerSide='right';$drawerSize='xl';$drawerTitle='Transaction details';$drawerDescription='Complete financial transaction information.';$drawerTrigger='<span class="hidden"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;$drawerHeaderBottom='';require BASE_PATH.'/resources/views/components/base/drawer.php'; ?>
