<?php declare(strict_types=1);
$fc='w-full rounded-xl border border-slate-200 px-4 py-3 text-sm text-secondary outline-none focus:border-primary focus:ring-2 focus:ring-primary/10 bg-white';
ob_start(); ?>
<form id="expense-form" method="post" action="/admin/expenses" class="space-y-4">
    <input type="hidden" name="csrf_token" value="<?= htmlspecialchars((string)$csrfToken) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="expense-form-id" value="0">
    <label class="block"><span class="mb-1.5 block text-sm font-semibold text-secondary">Expense category *</span><select required name="category" id="expense-category" class="<?= $fc ?>"><?php foreach($categories as $value=>$label): ?><option value="<?= htmlspecialchars((string)$value) ?>"><?= htmlspecialchars((string)$label) ?></option><?php endforeach; ?></select></label>
    <label class="block"><span class="mb-1.5 block text-sm font-semibold text-secondary">Title *</span><input required name="title" id="expense-title" maxlength="190" class="<?= $fc ?>" placeholder="e.g. Packaging materials"></label>
    <label class="block"><span class="mb-1.5 block text-sm font-semibold text-secondary">Amount (LKR) *</span><input required type="number" min="0.01" step="0.01" name="amount" id="expense-amount" class="<?= $fc ?>"></label>
    <label class="block"><span class="mb-1.5 block text-sm font-semibold text-secondary">Date *</span><input required type="date" name="expense_date" id="expense-expense_date" value="<?= date('Y-m-d') ?>" class="<?= $fc ?>"></label>
    <label class="block"><span class="mb-1.5 block text-sm font-semibold text-secondary">Notes (optional)</span><textarea name="description" id="expense-description" rows="3" class="<?= $fc ?>"></textarea></label>
</form>
<script>document.addEventListener('DOMContentLoaded',function(){var meta={};document.querySelectorAll('#expenses-table tbody tr[data-row]').forEach(function(row){var cell=row.querySelector('td[data-key="_meta"]');if(!cell)return;try{var value=JSON.parse(cell.textContent.trim());if(value&&value.id)meta[String(value.id)]=value;}catch(e){}});function reset(){document.getElementById('expense-form').reset();document.getElementById('expense-form-id').value='0';document.getElementById('expense-expense_date').value=new Date().toISOString().slice(0,10);document.getElementById('expense-save-btn').textContent='Save expense';}document.querySelector('[data-drawer-open="expense-drawer"]')?.addEventListener('click',function(e){if(!e.target.closest('[data-expense-edit]'))reset();});document.addEventListener('click',function(e){var button=e.target.closest('[data-expense-edit]');if(!button)return;var value=meta[button.getAttribute('data-expense-edit')];if(!value)return;document.getElementById('expense-form-id').value=value.id;document.getElementById('expense-category').value=value.category||'other';document.getElementById('expense-title').value=value.title||'';document.getElementById('expense-amount').value=value.amount||'';document.getElementById('expense-expense_date').value=value.expense_date||'';document.getElementById('expense-description').value=value.description||'';document.getElementById('expense-save-btn').textContent='Update expense';});});</script>
<?php $drawerBody=(string)ob_get_clean();$drawerFooter='<button id="expense-save-btn" type="submit" form="expense-form" class="rounded-xl bg-primary px-6 py-2.5 text-sm font-bold text-white hover:bg-secondary">Save expense</button>';$drawerId='expense-drawer';$drawerSide='right';$drawerSize='md';$drawerTitle='Add business expense';$drawerDescription='Non-product operating costs paid from business cash.';$drawerTrigger='<span class="hidden"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;$drawerHeaderBottom='';require BASE_PATH.'/resources/views/components/base/drawer.php'; ?>
