<?php declare(strict_types=1); ob_start(); ?>
<div class="space-y-4">
 <div id="order-total-card" class="rounded-2xl border border-primary/15 bg-primary/[0.04] p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.16em] text-primary">Order total</p><p id="order-view-total" class="mt-2 text-3xl font-black text-secondary"></p></div>
 <?php foreach ([['summary','Order & payment'],['items','Products'],['customer','Customer details'],['tracking','Delivery & tracking']] as [$key,$label]): ?>
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><button type="button" data-order-section="<?= $key ?>" class="flex w-full items-center justify-between px-5 py-4 text-left text-base font-bold text-secondary"><span><?= $label ?></span><svg class="h-4 w-4 transition" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="m6 9 6 6 6-6"/></svg></button><div id="order-section-<?= $key ?>" class="<?= $key === 'summary' ? '' : 'hidden' ?> border-t border-slate-200 p-5"></div></section>
 <?php endforeach; ?>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
 var basePath=<?= json_encode(app_base_path()) ?>;
 function esc(v){var n=document.createElement('div');n.textContent=v==null||v===''?'—':String(v);return n.innerHTML;}
 function money(v){return 'LKR '+Number(v||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2});}
 function field(l,v){return '<div class="rounded-xl border border-slate-100 bg-slate-50/60 px-4 py-3"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">'+esc(l)+'</p><p class="mt-1 text-sm font-semibold capitalize text-secondary">'+esc(v)+'</p></div>';}
 function localUrl(p){if(!p||/^https?:\/\//i.test(p))return p||'';p='/'+String(p).replace(/^\/?(?:public\/)?/,'');return basePath+p;}
 function statusActions(v){
  var action=<?= json_encode(app_url('/admin/orders')) ?>,csrf=<?= json_encode($csrfToken) ?>,redirect='/admin/orders?view='+encodeURIComponent(v.id)+'&section=tracking';
  function form(status,label){var current=String(v.order_status||'pending'),active=current===status,decision=status==='cancelled'?'cancel':status==='pending'?'payment_pending':(status==='confirmed'&&current==='pending'?'confirm':'advance_status');return '<form method="post" action="'+esc(action)+'"><input type="hidden" name="csrf_token" value="'+esc(csrf)+'"><input type="hidden" name="order_id" value="'+esc(v.id)+'"><input type="hidden" name="redirect_to" value="'+esc(redirect)+'"><input type="hidden" name="decision" value="'+esc(decision)+'">'+(!['cancelled','pending'].includes(status)?'<input type="hidden" name="order_status" value="'+esc(status)+'">':'')+(decision==='confirm'?'<input type="hidden" name="delivery_days" value="3">':'')+'<button type="submit" '+(active?'disabled':'')+' class="w-full rounded-xl border px-4 py-3 text-sm font-bold transition '+(active?'cursor-default border-primary bg-primary text-white':'border-slate-200 bg-white text-secondary hover:border-primary/30 hover:bg-primary/5 hover:text-primary')+'">'+esc(label)+(active?' · Current':'')+'</button></form>';}
  var options=[['pending','Pending'],['confirmed','Accepted'],['processing','Processing'],['ready','Ready'],['out_for_delivery','Out for delivery'],['delivered','Delivered'],['cancelled','Rejected']];
  var received=Number(v.payment_amount??v.amount??0),balance=Math.max(0,Number(v.grand_total||0)-received),paymentPending=String(v.payment_status||'pending')!=='paid'&&String(v.order_status||'pending')!=='cancelled';
  var paymentAction=paymentPending?'<div class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4"><p class="text-xs font-bold uppercase tracking-wider text-emerald-700">Payment update</p><p class="mt-1 text-sm text-emerald-800">Balance to receive: <strong>'+money(balance)+'</strong></p><form method="post" action="'+esc(action)+'" class="mt-4"><input type="hidden" name="csrf_token" value="'+esc(csrf)+'"><input type="hidden" name="order_id" value="'+esc(v.id)+'"><input type="hidden" name="redirect_to" value="'+esc(redirect)+'"><input type="hidden" name="decision" value="mark_paid"><button type="submit" class="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white transition hover:bg-emerald-700">Payment received</button></form></div>':'';
  return '<div><p class="text-sm text-slate-500">Select the current order status. Customer notification and inventory flow will update automatically.</p><div class="mt-5 grid gap-3 sm:grid-cols-2">'+options.map(function(option){return form(option[0],option[1]);}).join('')+'</div>'+paymentAction+'</div>';
 }
 document.addEventListener('click',function(e){
  var toggle=e.target.closest('[data-order-section]');if(toggle){var body=document.getElementById('order-section-'+toggle.dataset.orderSection);body.classList.toggle('hidden');toggle.querySelector('svg')?.classList.toggle('rotate-180');return;}
  var btn=e.target.closest('[data-order-view]');if(!btn)return;var cell=btn.closest('tr')?.querySelector('td[data-key="_meta"]'),v;if(!cell)return;try{v=JSON.parse(cell.textContent.trim());}catch(err){return;}
  var paid=Number(v.payment_amount??v.amount??0),total=Number(v.grand_total||0);
  document.getElementById('order-view-total').textContent=money(total);
  var receipt=v.receipt_path?'<a href="'+esc(localUrl(v.receipt_path))+'" target="_blank" class="mt-4 inline-flex rounded-xl border border-primary/20 px-4 py-2.5 text-sm font-bold text-primary hover:bg-primary/5">View payment receipt</a>':'';
  document.getElementById('order-section-summary').innerHTML='<div class="grid gap-3 sm:grid-cols-2">'+field('Order status',String(v.order_status||'pending').replaceAll('_',' '))+field('Payment method',String(v.method||v.payment_method||'—').replaceAll('_',' '))+field('Payment status',String(v.payment_status||'pending').replaceAll('_',' '))+field('Amount received',money(paid))+field('Balance due',money(Math.max(0,total-paid)))+field('Date',v.payment_date||v.created_at)+'</div>'+receipt;
  var items=Array.isArray(v.items)?v.items:[];document.getElementById('order-section-items').innerHTML=items.length?items.map(function(i){return '<div class="flex items-center gap-4 border-b border-slate-100 py-3 last:border-0"><img src="'+esc(localUrl(i.product_image||'/assets/images/hero_slide_1.jpg'))+'" class="h-14 w-14 rounded-xl object-cover ring-1 ring-slate-200" alt=""><div class="min-w-0 flex-1"><p class="font-bold text-secondary">'+esc(i.product_name)+'</p><p class="text-xs text-slate-500">'+esc(i.sku)+' · Qty '+esc(i.quantity)+' × '+money(i.unit_price)+'</p></div><p class="font-bold text-secondary">'+money(Number(i.unit_price||0)*Number(i.quantity||0))+'</p></div>';}).join(''):'<p class="text-sm text-slate-500">No products recorded.</p>';
  document.getElementById('order-section-customer').innerHTML='<div class="grid gap-3 sm:grid-cols-2">'+field('Customer',v.customer_name)+field('Phone',v.customer_phone)+field('Email',v.customer_email)+field('Recipient',v.recipient_name||v.customer_name)+field('Recipient phone',v.recipient_phone||v.customer_phone)+field('Delivery date',v.delivery_date)+field('Address',[v.delivery_address_line_1,v.delivery_address_line_2].filter(Boolean).join(', '))+field('City / district',[v.delivery_city,v.delivery_district].filter(Boolean).join(', '))+'</div>';
  var statusMode=btn.dataset.orderTarget==='tracking';
  document.getElementById('order-section-tracking').innerHTML=statusMode?statusActions(v):'<div class="grid gap-3 sm:grid-cols-2">'+field('Delivery status',String(v.delivery_status||'pending').replaceAll('_',' '))+field('Tracking code',v.tracking_code)+field('Courier',v.courier_service_name)+field('Courier tracking #',v.courier_tracking_number)+field('Dispatch date',v.dispatch_date)+field('Expected delivery',v.expected_delivery_date)+field('Delivered date',v.delivered_date)+'</div>';
  document.getElementById('order-total-card').classList.toggle('hidden',statusMode);document.getElementById('order-view-drawer-title').textContent=statusMode?'Order status':'Order details';var description=document.getElementById('order-view-drawer-title').nextElementSibling;if(description)description.textContent=statusMode?'Manage this order status only.':'Review the complete order and expand each section.';document.getElementById('order-drawer-receipt').classList.toggle('hidden',statusMode);
  var targetSection=statusMode?'tracking':'summary',labels={summary:'Order & payment',items:'Products',customer:'Customer details',tracking:statusMode?'Order status':'Delivery & tracking'};document.querySelectorAll('[data-order-section]').forEach(function(sectionButton){var key=sectionButton.dataset.orderSection,section=sectionButton.closest('section'),expanded=key===targetSection;section.classList.toggle('hidden',statusMode&&!expanded);sectionButton.querySelector('span').textContent=labels[key]||key;document.getElementById('order-section-'+key).classList.toggle('hidden',!expanded);sectionButton.querySelector('svg')?.classList.toggle('rotate-180',expanded);});
  document.getElementById('order-drawer-receipt').href=<?= json_encode(app_url('/admin/orders/receipt?id=')) ?>+v.id;
 });
 var params=new URLSearchParams(window.location.search),requested=params.get('view');if(requested){var section=params.get('section')==='tracking'?'tracking':'summary',target=document.querySelector('[data-order-view][data-order-target="'+section+'"][data-order-id="'+CSS.escape(requested)+'"]');if(target)setTimeout(function(){target.click();},0);}
});
</script>
<?php
$drawerBody=(string)ob_get_clean();
$drawerFooter='<button type="button" data-drawer-close class="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold text-secondary hover:bg-slate-50">Close</button><a id="order-drawer-receipt" target="_blank" class="rounded-xl border border-primary/20 px-5 py-2.5 text-sm font-bold text-primary hover:bg-primary/5">Print receipt</a>';
$drawerId='order-view-drawer';$drawerSide='right';$drawerSize='xl';$drawerTitle='Order details';$drawerDescription='Review the complete order and expand each section.';$drawerTrigger='<span class="hidden"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;$drawerHeaderBottom='';
require BASE_PATH.'/resources/views/components/base/drawer.php';
?>
