<?php declare(strict_types=1); ob_start(); ?>
<div class="space-y-4">
 <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Order</p><h4 id="order-view-number" class="mt-2 text-2xl font-bold text-secondary"></h4><p id="order-view-created" class="mt-1 text-sm text-slate-500"></p></div><div class="flex flex-wrap gap-2"><span id="order-view-status" class="rounded-full px-3 py-1 text-xs font-bold"></span><span id="order-view-payment-status" class="rounded-full px-3 py-1 text-xs font-bold"></span></div></div><p id="order-view-total" class="mt-5 text-2xl font-black text-primary"></p></div>
 <?php foreach([['summary','Order summary'],['items','Items'],['customer','Customer & delivery'],['payment','Payment']] as [$key,$label]): ?>
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><button type="button" data-order-section="<?= $key ?>" class="flex w-full items-center justify-between px-5 py-4 text-left text-base font-bold text-secondary"><span><?= $label ?></span><svg class="h-4 w-4 transition" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="m6 9 6 6 6-6"/></svg></button><div id="order-section-<?= $key ?>" class="<?= $key==='summary'?'':'hidden' ?> border-t border-slate-200 p-5"></div></section>
 <?php endforeach; ?>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
 var esc=function(v){var d=document.createElement('div');d.textContent=v==null||v===''?'—':String(v);return d.innerHTML;};
 var money=function(v){return 'LKR '+Number(v||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2});};
 function field(label,value){return '<div class="rounded-xl bg-slate-50 px-4 py-3"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">'+esc(label)+'</p><p class="mt-1 text-sm font-semibold text-secondary">'+esc(value)+'</p></div>';}
 function badge(el,status,type){var good=type==='payment'?status==='paid':['delivered','confirmed'].includes(status),bad=['cancelled','refunded','failed'].includes(status);el.textContent=String(status||'pending').replaceAll('_',' ');el.className='rounded-full px-3 py-1 text-xs font-bold '+(good?'bg-emerald-50 text-emerald-700':bad?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700');}
 document.addEventListener('click',function(e){
  var section=e.target.closest('[data-order-section]');if(section){var body=document.getElementById('order-section-'+section.dataset.orderSection);body.classList.toggle('hidden');section.querySelector('svg')?.classList.toggle('rotate-180');return;}
  var btn=e.target.closest('[data-order-view]');if(!btn)return;var cell=btn.closest('tr')?.querySelector('td[data-key="_meta"]');if(!cell)return;var v;try{v=JSON.parse(cell.textContent.trim());}catch(err){return;}
  document.getElementById('order-view-number').textContent=v.order_number||'';document.getElementById('order-view-created').textContent=v.created_at||'';document.getElementById('order-view-total').textContent=money(v.grand_total);badge(document.getElementById('order-view-status'),v.order_status,'order');badge(document.getElementById('order-view-payment-status'),v.payment_status,'payment');
  document.getElementById('order-section-summary').innerHTML='<div class="grid gap-3 sm:grid-cols-2">'+field('Subtotal',money(v.subtotal))+field('Discount',money(v.discount_total))+field('Delivery',money(v.delivery_charge))+field('Grand total',money(v.grand_total))+'</div>';
  var items=Array.isArray(v.items)?v.items:[];document.getElementById('order-section-items').innerHTML=items.length?items.map(function(i){return '<div class="flex items-center gap-4 border-b border-slate-100 py-3 last:border-0"><img src="'+esc(i.product_image||'/assets/images/hero_slide_1.jpg')+'" class="h-14 w-14 rounded-xl object-cover" alt=""><div class="min-w-0 flex-1"><p class="font-bold text-secondary">'+esc(i.product_name)+'</p><p class="text-xs text-slate-500">'+esc(i.sku)+' · Qty '+esc(i.quantity)+'</p></div><p class="font-bold text-secondary">'+money(Number(i.unit_price||0)*Number(i.quantity||0))+'</p></div>';}).join(''):'<p class="text-sm text-slate-500">No items recorded.</p>';
  document.getElementById('order-section-customer').innerHTML='<div class="grid gap-3 sm:grid-cols-2">'+field('Customer',v.customer_name)+field('Phone',v.customer_phone)+field('Recipient',v.recipient_name||v.customer_name)+field('Recipient phone',v.recipient_phone||v.customer_phone)+field('Address',[v.delivery_address_line_1,v.delivery_address_line_2].filter(Boolean).join(', '))+field('City / district',[v.delivery_city,v.delivery_district].filter(Boolean).join(', '))+field('Delivery date',v.delivery_date)+'</div>';
  document.getElementById('order-section-payment').innerHTML='<div class="grid gap-3 sm:grid-cols-2">'+field('Method',String(v.method||v.payment_method||'—').replaceAll('_',' '))+field('Payment status',String(v.payment_status||'pending').replaceAll('_',' '))+field('Paid amount',money(v.payment_amount||v.amount))+field('Verification',String(v.payment_verification_status||'pending').replaceAll('_',' '))+'</div>';
  document.getElementById('order-drawer-receipt').href=<?= json_encode(app_url('/admin/orders/receipt?id=')) ?>+v.id;document.getElementById('order-drawer-manage').href=<?= json_encode(app_url('/admin/orders/view?id=')) ?>+v.id;
 });
 var requested=new URLSearchParams(window.location.search).get('view');if(requested){var target=document.querySelector('[data-order-view][data-order-id="'+CSS.escape(requested)+'"]');if(target)setTimeout(function(){target.click();},0);}
});
</script>
<?php $drawerBody=(string)ob_get_clean();$drawerFooter='<a id="order-drawer-receipt" target="_blank" class="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold text-secondary hover:bg-slate-50">Print receipt</a><a id="order-drawer-manage" class="rounded-xl bg-primary px-6 py-2.5 text-sm font-bold text-white hover:bg-secondary">Manage order</a>';$drawerId='order-view-drawer';$drawerSide='right';$drawerSize='xl';$drawerTitle='Order details';$drawerDescription='Review the order and expand each section.';$drawerTrigger='<span class="hidden"></span>';$drawerStatic=false;$drawerCloseOnEsc=true;$drawerShowCloseButton=true;$drawerOverlay=true;$drawerHeaderBottom='';require BASE_PATH.'/resources/views/components/base/drawer.php'; ?>
